### PR TITLE
fix: dashboard tab styling

### PR DESCRIPTION
**Pull request by corquaid**
Description
---
- Adjusting dashboard tabs to have correct horizontal margin.
- Adding hover state styling to dashboard tabs (it's _really_ subtle but that's the design from Figma)

Motivation and Context
---
#132

How Has This Been Tested?
---
Figma:

https://user-images.githubusercontent.com/69508715/166886895-4cb0e7cd-e27c-4cdd-9615-f4f2b5df899c.mov

App:

https://user-images.githubusercontent.com/69508715/166890479-18765974-6b84-48e7-9199-4adf2eb92f5a.mov

### CODE REVIEW

**Comment by tarnas14** [comment]
I think that hover state for active tab should not have bottom-border radius
the darker background would then align with the bottom border and look a bit more polished?

wdyt?

**Comment by corquaid** [comment]
> I think that hover state for active tab should not have bottom-border radius the darker background would then align with the bottom border and look a bit more polished?
> 
> wdyt?

Yes, I thought about that a bit also, I was thinking that if the tab is selected then it could have no bottom-border radius to match the selected border nicely, and if the tab is unselected then it has the full border-radius.

If I remove the bottom-radius completely it looks a bit meh on the unselected tabs:

image

Here's a green version for more clarity:

image

**Comment by tomaszantas** [comment]
> > I think that hover state for active tab should not have bottom-border radius the darker background would then align with the bottom border and look a bit more polished?
> > wdyt?
> 
> Yes, I thought about that a bit also, I was thinking that if the tab is selected then it could have no bottom-border radius to match the selected border nicely, and if the tab is unselected then it has the full border-radius.
> 
> If I remove the bottom-radius completely it looks a bit meh on the unselected tabs:
> 
> image

Yeah, I agree that small border radius will fit nicely

**Comment by tomaszantas** [comment]
@corquaid One more comment:

can we remove the `margin-right` from the last tab?

```
&:last-child {
  margin-right: 0;
}
```

Tabs will need less space so it may fit better on smaller screens.

**Comment by tarnas14** [comment]
> > I think that hover state for active tab should not have bottom-border radius the darker background would then align with the bottom border and look a bit more polished?
> > wdyt?
> 
> Yes, I thought about that a bit also, I was thinking that if the tab is selected then it could have no bottom-border radius to match the selected border nicely, and if the tab is unselected then it has the full border-radius.
> 
> If I remove the bottom-radius completely it looks a bit meh on the unselected tabs:
> 
> image
> 
> Here's a green version for more clarity:
> 
> image

that's what I meant - only the selected/active without bottom radius

**Review by tarnas14 — APPROVED** [review]
ship it

**Pull request merged**
